export const GET_COLLECTIONS_REQUEST = 'GET_COLLECTIONS_REQUEST';
export const GET_COLLECTIONS_SUCCESS = 'GET_COLLECTIONS_SUCCESS';
export const GET_COLLECTIONS_FAILURE = 'GET_COLLECTIONS_FAILURE';

export const DELETE_COLLECTIONS_REQUEST = 'DELETE_COLLECTIONS_REQUEST';
export const DELETE_COLLECTIONS_SUCCESS = 'DELETE_COLLECTIONS_SUCCESS';
export const DELETE_COLLECTIONS_FAILURE = 'DELETE_COLLECTIONS_FAILURE';

export const SAVE_COLLECTIONS_REQUEST = 'SAVE_COLLECTIONS_REQUEST';
export const SAVE_COLLECTIONS_SUCCESS = 'SAVE_COLLECTIONS_SUCCESS';
export const SAVE_COLLECTIONS_FAILURE = 'SAVE_COLLECTIONS_FAILURE';

export const OPEN_COLLECTION_FORM = 'OPEN_COLLECTION_FORM';
export const CLOSE_COLLECTION_FORM = 'CLOSE_COLLECTION_FORM';
export const SELECT_COLLECTION = 'SELECT_COLLECTION';

export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';

export const DELETE_BOOK_FROM_COLLECTION_REQUEST = 'DELETE_BOOK_FROM_COLLECTION_REQUEST';
export const DELETE_BOOK_FROM_COLLECTION_SUCCESS = 'DELETE_BOOK_FROM_COLLECTION_SUCCESS';
export const DELETE_BOOK_FROM_COLLECTION_FAILURE = 'DELETE_BOOK_FROM_COLLECTION_FAILURE';

export const ADD_BOOK_TO_COLLECTION_REQUEST = 'ADD_BOOK_TO_COLLECTION_REQUEST';
export const ADD_BOOK_TO_COLLECTION_SUCCESS = 'ADD_BOOK_TO_COLLECTION_SUCCESS';
export const ADD_BOOK_TO_COLLECTION_FAILURE = 'ADD_BOOK_TO_COLLECTION_FAILURE';